### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JimmyBassy** [CredixYt/Credixware#2]
Undetected VMT hooks? And if so can you tell me how to check this for other sources. I want to see the difference between the standard VMT hooking and the "undetected" one.

**Comment by CredixYt** [comment]
VAC detecting hooking is not a very well researched topic and unfortunately, we don't have much information that is based on evidence, only speculations. Some people say that the new VAC module (which checks for hooks) is only streamed to low trust factor players. Some people say that it checks random VTables and the ones used by known public cheats, so if you are unlucky VAC, might check the one you have hooked. Others say that it depends on you "hook" method. One thing which is true for sure is that I and some friends have used Credixware and not of us got VAC banned yet, so I think it's safe to say that **Credixware, including the VMT hook function, is undetected.**
