### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by SnakeyLuck** [CredixYt/Credixware#3]
crashes alot in games with players works fine with bots. and certain features crash game like glow did for me.

**Comment by CredixYt** [comment]
Unfortunately as new CS:GO updates roll out offsets and indexes change, which can influence how the cheat work. As you can see, the current update (Beta v0.4) is quite outdated meaning that you will have to update some parts (like offsets) for it to work. Currently, I am working on releasing a newer version which will fix most of the problems
